
# html lang
language: zh_CN

# main menu navigation
menu:
  关于: /about
  RSS: /feed.xml

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css
- /css/springFestival.css

# scripts loaded in the end of the body
scripts:
- /js/white.js
